// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TraceAgentApi.Trace.Persistence;

#nullable disable

namespace TraceAgentApi.Migrations
{
    [DbContext(typeof(TraceDbContext))]
    [Migration("20260721162534_AddRunEmbeddings")]
    partial class AddRunEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.AgentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCostEur")
                        .HasColumnType("numeric");

                    b.Property<string>("FinalAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasPiiViolation")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PiiSummaryJson")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.AuditEntryEntity", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Sequence");

                    b.HasIndex("ResourceId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.EvalRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CasesPassed")
                        .HasColumnType("integer");

                    b.Property<int>("CasesTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ScorePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("eval_runs", (string)null);
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.RunEmbeddingEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndexedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RunId");

                    b.ToTable("run_embeddings", (string)null);
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.TraceStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.ToTable("trace_steps", (string)null);
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.RunEmbeddingEntity", b =>
                {
                    b.HasOne("TraceAgentApi.Trace.Persistence.AgentRunEntity", "Run")
                        .WithOne()
                        .HasForeignKey("TraceAgentApi.Trace.Persistence.RunEmbeddingEntity", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.TraceStepEntity", b =>
                {
                    b.HasOne("TraceAgentApi.Trace.Persistence.AgentRunEntity", "AgentRun")
                        .WithMany("Steps")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("TraceAgentApi.Trace.Persistence.AgentRunEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
